export const data = {
  title: 'Kringloop Label 2024',
  description: 'Kringloop Label 2024',
  year: 2024,
  valid: true,
  sections: [
    {
      title: 'BASISPOPULATIE',
      position: 1,
      survey: 1,
      canSkip: false,
      subSections: [
        {
          title: 'Ooien',
          position: 1,
          section: 1,
          questions: [
            {
              text: 'Wat is het ras van jouw schapen?',
              type: 'MULTIPLE_CHOICE',
              answerElement: 'DROPDOWN',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Texelaar',
                  score: 1,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Hoeveel ooien hebben in 2023 gelammerd',
              type: 'OPEN_ENDED',
              answerElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel ooien zijn er in het vorige jaar toegelaten bij de ram',
              type: 'OPEN_ENDED',
              answerElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              canSkip: false,
              graded: false,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'DEKRAMMEN',
          position: 2,
          section: 1,
          questions: [
            {
              text: 'Hoeveel dekrammen zijn er in afgelopen dekseizoen ingezet?',
              type: 'OPEN_ENDED',
              answerElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'NIET IN PRODUCTIE',
          position: 3,
          section: 1,
          questions: [
            {
              text: 'Hoeveel schapen heb je die niet voor productie worden in gezet?',
              type: 'OPEN_ENDED',
              answerElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel weidelammeren zijn er in 2023 aangekocht?',
              type: 'OPEN_ENDED',
              answerDataType: 'INTEGER',
              answerElement: 'INPUTBOX',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Welk percentage van de lammeren zijn er verkocht als weidelam in 2023',
              type: 'OPEN_ENDED',
              answerElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'PERCENTAGE',
              canSkip: true,
              graded: false,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'PRODUCTIEDOELEN',
          position: 4,
          section: 1,
          questions: [
            {
              text: 'Wat zijn je productiedoelen in deze koppel?',
              type: 'MULTIPLE_CHOICE',
              answerElement: 'CHECKBOX',
              answerDataType: 'INTEGER',
              canSkip: false,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Vlees',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Zuivel',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Wol',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Begrazing / natuurbeheer',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Anders',
                  score: 1,
                  questionId: 1,
                },
              ],
            },
          ],
        },
        {
          title: 'Toelichting op deze sectie',
          position: 5,
          section: 1,
          questions: [
            {
              text: 'Toelichting voor de beoordelaar',
              type: 'OPEN_ENDED',
              answerElement: 'TEXTAREA',
              answerDataType: 'INTEGER',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
      ],
    },
  ],
};
