export const data = {
  title: 'Kringloop Label 2024',
  description: 'Kringloop Label 2024',
  year: 2024,
  valid: true,
  sections: [
    {
      title: 'BASISPOPULATIE',
      position: 1,
      survey: 1,
      canSkip: false,
      subSections: [
        {
          title: 'Ooien',
          position: 1,
          section: 1,
          questions: [
            {
              text: 'Wat is het ras van jouw schapen?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'DROPDOWN',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Texelaar',
                  score: 1,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Hoeveel ooien hebben in 2023 gelammerd',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel ooien zijn er in het vorige jaar toegelaten bij de ram',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'DEKRAMMEN',
          position: 2,
          section: 1,
          questions: [
            {
              text: 'Hoeveel dekrammen zijn er in afgelopen dekseizoen ingezet?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'NIET IN PRODUCTIE',
          position: 3,
          section: 1,
          questions: [
            {
              text: 'Hoeveel schapen heb je die niet voor productie worden in gezet?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel weidelammeren zijn er in 2023 aangekocht?',
              type: 'OPEN_ENDED',
              answerDataType: 'INTEGER',
              htmlElement: 'INPUTBOX',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Welk percentage van de lammeren zijn er verkocht als weidelam in 2023',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'PERCENTAGE',
              canSkip: true,
              graded: false,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'PRODUCTIEDOELEN',
          position: 4,
          section: 1,
          questions: [
            {
              text: 'Wat zijn je productiedoelen in deze koppel?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'CHECKBOX',
              answerDataType: 'INTEGER',
              canSkip: false,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Vlees',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Zuivel',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Wol',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Begrazing / natuurbeheer',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Anders',
                  score: 1,
                  questionId: 1,
                },
              ],
            },
          ],
        },
        {
          title: 'Toelichting op deze sectie',
          position: 5,
          section: 1,
          questions: [
            {
              text: 'Toelichting voor de beoordelaar',
              type: 'OPEN_ENDED',
              htmlElement: 'TEXTAREA',
              answerDataType: 'INTEGER',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
      ],
    },
    {
      title: 'BEDRIJFSPRESTATIES',
      position: 2,
      survey: 1,
      canSkip: true,
      subSections: [
        {
          title: 'VLEES',
          position: 1,
          section: 2,
          questions: [
            {
              text: 'Hoeveel lammeren zijn er levend geboren in 2023?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel lammeren zijn er dood geboren in 2023?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel afvoermeldingen zijn er in 2023 gedaan?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoe oud zijn de lammeren gemiddeld als ze geslacht worden?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 4,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel exportmeldingen zijn er in 2023 gedaan?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'STRING',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 5,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel aanvoermeldingen zijn er in 2023 gedaan?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 6,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Netto amount of sells on the farm',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'FLOAT',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 7,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel dieren zijn er gestorven in 2023?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'NUT',
              canSkip: false,
              graded: false,
              position: 8,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'GEWICHT',
          position: 2,
          section: 2,
          questions: [
            {
              text: 'Wat is het gemiddelde geboortegewicht?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Wat is het gemiddelde gewicht op 8 weken?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Wat is het gemiddelde gewicht op 20 weken?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              canSkip: false,
              graded: false,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'WOL',
          position: 3,
          section: 2,
          questions: [
            {
              text: 'Hoeveel kilogram wol is er in 2023 afgeleverd?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'ZUIVEL',
          position: 4,
          section: 2,
          questions: [
            {
              text: 'Hoeveel kilogram vet is er in 2023 afgeleverd voor humane consumptie?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel kilogram eiwit is er in 2023 afgeleverd voor humane consumptie?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'BEGRAZING',
          position: 5,
          section: 2,
          questions: [
            {
              text: 'Hoeveel ha grond is er beheerd middels een begrazingscontract?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'SQUARE',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'Toelichting op deze sectie',
          position: 6,
          section: 2,
          questions: [
            {
              text: 'Toelichting voor de beoordelaar',
              type: 'OPEN_ENDED',
              htmlElement: 'TEXTAREA',
              answerDataType: 'INTEGER',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
      ],
    },
    {
      title: 'WEIDEBEHEER',
      position: 3,
      survey: 1,
      canSkip: true,
      subSections: [
        {
          title: 'PERCELEN',
          position: 1,
          section: 3,
          questions: [
            {
              text: 'Wat is het totaal aantal hectares beschikbaar voor beweiding in de zomer?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'FLOAT',
              inputIcon: 'SQUARE',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Wat is/zijn de type(n) gebruikte gronden?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'CHECKBOX',
              answerDataType: 'STRING',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Conventioneel grasland',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Grasklaver',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Kruidenrijk',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Uitgestelde maaidatum',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Natuurland',
                  score: 1,
                  questionId: 1,
                },
              ],
            },
          ],
        },
        {
          title: 'STAL',
          position: 2,
          section: 2,
          questions: [
            {
              text: 'Hoeveel weken staan de lammeren op stal?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel weken staan de fokooien op stal?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Welk percentage van de lammeren wordt afgemest op stal?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'PERCENTAGE',
              canSkip: false,
              graded: false,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'OVERIG',
          position: 3,
          section: 3,
          questions: [
            {
              text: 'Pas je beregening toe?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              graded: true,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 0,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 1,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Gebruik je kunstmest met stikstof of fosfaat?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              graded: true,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 0,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 3,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Wordt er ruwvoer of snijmais aangekocht?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              graded: true,
              position: 3,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 0,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 3,
                  questionId: 1,
                },
              ],
            },
          ],
        },
        {
          title: 'Toelichting op deze sectie',
          position: 4,
          section: 3,
          questions: [
            {
              text: 'Toelichting voor de beoordelaar',
              type: 'OPEN_ENDED',
              htmlElement: 'TEXTAREA',
              answerDataType: 'INTEGER',
              canSkip: false,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
      ],
    },
    {
      title: 'Voeding',
      position: 4,
      survey: 1,
      canSkip: true,
      subSections: [
        {
          title: 'PERCELEN',
          position: 1,
          section: 3,
          questions: [
            {
              text: 'Hoeveel kilogram in brokvorm is er in 2023 aangekocht?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'FLOAT',
              inputIcon: 'KG',
              canSkip: false,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Wat is het eiwitpercentage van de gebruikte brok?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'FLOAT',
              inputIcon: 'PERCENTAGE',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Hoeveel kilogram melkpoeder is er in 2023 aangekocht?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'FLOAT',
              inputIcon: 'KG',
              canSkip: false,
              graded: false,
              position: 2,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
      ],
    },
    {
      title: 'GEZONDHEID & MEDICIJNGEBRUIK',
      position: 5,
      survey: 1,
      canSkip: true,
      subSections: [
        {
          title: '',
          position: 1,
          section: 5,
          questions: [
            {
              text: 'Ben je gecertificeerd zwoegerziektevrij?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 1,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 3,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 0,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Gebruik je middelen tegen coccidiose?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 2,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Groepsniveau',
                  score: 0,
                  questionId: 1,
                },
                {
                  text: 'Individueel',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 3,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Gebruik je de insecticide Butox, Spotinor, Deltanil of een ander product met werkzame stof Deltamethrin?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 3,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Groepsniveau',
                  score: 0,
                  questionId: 1,
                },
                {
                  text: 'Individueel',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 3,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Gebruik je de insecticide Neocidol, Vetozinon of een ander product met werkzame stof Diazinon?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 4,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Groepsniveau',
                  score: 0,
                  questionId: 1,
                },
                {
                  text: 'Individueel',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 3,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Gebruik je voetbaden met koper- of zinkzulfaat?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 4,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Nee',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Ja',
                  score: 0,
                  questionId: 1,
                },
              ],
            },
          ],
        },
        {
          title: 'Maagdarmwormen',
          position: 2,
          section: 5,
          questions: [
            {
              text: 'Heb je afgelopen jaar mestonderzoek op maagdarmwormen laten doen?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 1,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 0,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Heb je inzicht in de resistentiepatronen tegen ontwormingsmiddelen op jouw bedrijf?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 2,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Nee',
                  score: 0,
                  questionId: 1,
                },
                {
                  text: 'Ja',
                  score: 2,
                  questionId: 1,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      title: 'NATUUR & OMGEVING',
      position: 6,
      survey: 1,
      canSkip: true,
      subSections: [
        {
          title: '',
          position: 1,
          section: 5,
          questions: [
            {
              text: 'Wordt er bodemonderzoek gedaan of wordt op een andere manier aandacht geschonken aan bodemgezondheid- en leven?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 1,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 3,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 0,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Wordt er bij het maaien rekening gehouden met vogels en (ree)wild?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              canSkip: false,
              graded: true,
              position: 2,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 3,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 0,
                  questionId: 1,
                },
              ],
            },
          ],
        },
        {
          title: 'OVERIG',
          position: 2,
          section: 5,
          questions: [
            {
              text: 'Gebruikt je groene stroom/wek je eigen stroom op?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              graded: true,
              canSkip: false,
              position: 1,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 1,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 0,
                  questionId: 1,
                },
              ],
            },
            {
              text: 'Heb je je wagenpark/trekkerpark geelectrificeerd?',
              type: 'MULTIPLE_CHOICE',
              htmlElement: 'RADIO',
              answerDataType: 'STRING',
              graded: true,
              position: 2,
              canSkip: false,
              maximumScore: 3,
              surveyId: 1,
              subSectionId: 1,
              choices: [
                {
                  text: 'Ja',
                  score: 3,
                  questionId: 1,
                },
                {
                  text: 'Nee',
                  score: 0,
                  questionId: 1,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      title: 'FOKKERIJ',
      position: 7,
      survey: 1,
      canSkip: true,
      subSections: [
        {
          title: '',
          position: 1,
          section: 5,
          questions: [
            {
              text: 'Wat is de gemiddelde fokwaarde voor het 8-wekengewicht van de lammeren over afgelopen jaar?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Wat is de gemiddelde fokwaarde voor het 20-weken gewicht van de lammeren over afgelopen jaar?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'KG',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
        {
          title: 'FOKOOIEN MET EIGEN METINGEN',
          position: 2,
          section: 5,
          questions: [
            {
              text: 'Wat is het percentage van de fokooien met een fokwaarde voor wormresistentie?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'PERCENTAGE',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
            {
              text: 'Wat is het percentage van de fokooien met methaanmeting?',
              type: 'OPEN_ENDED',
              htmlElement: 'INPUTBOX',
              answerDataType: 'INTEGER',
              inputIcon: 'PERCENTAGE',
              canSkip: true,
              graded: false,
              position: 1,
              maximumScore: 1,
              surveyId: 1,
              subSectionId: 1,
            },
          ],
        },
      ],
    },
  ],
};
